/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminStats {
  'totalPNREnquiries' : bigint,
  'totalTourEnquiries' : bigint,
  'totalFlightEnquiries' : bigint,
  'totalBookings' : bigint,
  'totalVisaEnquiries' : bigint,
  'totalUsers' : bigint,
}
export interface FlightEnquiry {
  'id' : bigint,
  'customerName' : string,
  'status' : string,
  'destination' : string,
  'cabinClass' : [] | [string],
  'tripType' : TripType,
  'infantsCount' : bigint,
  'adultsCount' : bigint,
  'customerPhone' : string,
  'departureDate' : string,
  'specialRequests' : [] | [string],
  'origin' : string,
  'childrenCount' : bigint,
  'customerEmail' : [] | [string],
  'returnDate' : [] | [string],
}
export interface FlightEnquiryInput {
  'customerName' : string,
  'destination' : string,
  'cabinClass' : [] | [string],
  'tripType' : TripType,
  'infantsCount' : bigint,
  'adultsCount' : bigint,
  'customerPhone' : string,
  'departureDate' : string,
  'specialRequests' : [] | [string],
  'origin' : string,
  'childrenCount' : bigint,
  'customerEmail' : [] | [string],
  'returnDate' : [] | [string],
}
export interface PNREnquiry {
  'id' : bigint,
  'customerName' : string,
  'customerPhone' : string,
  'pnrNumber' : string,
  'notes' : [] | [string],
  'travelDate' : [] | [string],
  'airline' : string,
  'customerEmail' : [] | [string],
}
export interface PNREnquiryInput {
  'customerName' : string,
  'customerPhone' : string,
  'pnrNumber' : string,
  'notes' : [] | [string],
  'travelDate' : [] | [string],
  'airline' : string,
  'customerEmail' : [] | [string],
}
export type SessionToken = string;
export interface TourEnquiry {
  'id' : bigint,
  'customerName' : string,
  'status' : string,
  'adultsCount' : bigint,
  'customerPhone' : string,
  'specialRequests' : [] | [string],
  'travelDate' : string,
  'tourPackage' : string,
  'childrenCount' : bigint,
  'budget' : [] | [string],
  'customerEmail' : [] | [string],
}
export interface TourEnquiryInput {
  'customerName' : string,
  'adultsCount' : bigint,
  'customerPhone' : string,
  'specialRequests' : [] | [string],
  'travelDate' : string,
  'tourPackage' : string,
  'childrenCount' : bigint,
  'budget' : [] | [string],
  'customerEmail' : [] | [string],
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type TripType = { 'isFlexible' : null } |
  { 'returnTrip' : null } |
  { 'oneWay' : null };
export interface User {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'passwordHash' : string,
  'isAdmin' : boolean,
  'phone' : [] | [string],
}
export interface UserBooking {
  'customerName' : string,
  'destination' : string,
  'cabinClass' : string,
  'paymentStatus' : string,
  'bookingId' : bigint,
  'tripType' : string,
  'infantsCount' : bigint,
  'adultsCount' : bigint,
  'customerPhone' : string,
  'departureDate' : string,
  'pnrNumber' : [] | [string],
  'userId' : bigint,
  'createdAt' : bigint,
  'origin' : string,
  'bookingStatus' : string,
  'amadeusFlightInfo' : [] | [string],
  'childrenCount' : bigint,
  'customerEmail' : string,
  'returnDate' : [] | [string],
}
export interface UserBookingInput {
  'customerName' : string,
  'destination' : string,
  'cabinClass' : string,
  'tripType' : string,
  'infantsCount' : bigint,
  'adultsCount' : bigint,
  'customerPhone' : string,
  'departureDate' : string,
  'origin' : string,
  'childrenCount' : bigint,
  'customerEmail' : string,
  'returnDate' : [] | [string],
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VisaEnquiry {
  'id' : bigint,
  'customerName' : string,
  'status' : string,
  'country' : string,
  'customerPhone' : string,
  'visaType' : string,
  'travelDate' : string,
  'passportNumber' : [] | [string],
  'customerEmail' : [] | [string],
  'specialNotes' : [] | [string],
}
export interface VisaEnquiryInput {
  'customerName' : string,
  'country' : string,
  'customerPhone' : string,
  'visaType' : string,
  'travelDate' : string,
  'passportNumber' : [] | [string],
  'customerEmail' : [] | [string],
  'specialNotes' : [] | [string],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAdminStats' : ActorMethod<[SessionToken], AdminStats>,
  'getAllBookings' : ActorMethod<[SessionToken], Array<UserBooking>>,
  'getAllFlightEnquiries' : ActorMethod<
    [SessionToken],
    Array<[bigint, FlightEnquiry]>
  >,
  'getAllPNREnquiries' : ActorMethod<
    [SessionToken],
    Array<[bigint, PNREnquiry]>
  >,
  'getAllTourEnquiries' : ActorMethod<
    [SessionToken],
    Array<[bigint, TourEnquiry]>
  >,
  'getAllUsers' : ActorMethod<[SessionToken], Array<[bigint, User]>>,
  'getAllVisaEnquiries' : ActorMethod<
    [SessionToken],
    Array<[bigint, VisaEnquiry]>
  >,
  'getAmadeusFlightInfo' : ActorMethod<[SessionToken, string, string], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserBookings' : ActorMethod<[SessionToken], Array<UserBooking>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'loginUser' : ActorMethod<[string, string], SessionToken>,
  'registerUser' : ActorMethod<
    [string, string, string, [] | [string]],
    SessionToken
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveUserBooking' : ActorMethod<[SessionToken, UserBookingInput], bigint>,
  'submitFlightEnquiry' : ActorMethod<[FlightEnquiryInput], bigint>,
  'submitPNREnquiry' : ActorMethod<[PNREnquiryInput], bigint>,
  'submitTourEnquiry' : ActorMethod<[TourEnquiryInput], bigint>,
  'submitVisaEnquiry' : ActorMethod<[VisaEnquiryInput], bigint>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateBookingPNR' : ActorMethod<[SessionToken, bigint, string], undefined>,
  'updateBookingPaymentStatus' : ActorMethod<
    [SessionToken, bigint, string],
    undefined
  >,
  'updateBookingStatus' : ActorMethod<
    [SessionToken, bigint, string],
    undefined
  >,
  'updateFlightEnquiryStatus' : ActorMethod<
    [SessionToken, bigint, string],
    undefined
  >,
  'updateTourEnquiryStatus' : ActorMethod<
    [SessionToken, bigint, string],
    undefined
  >,
  'updateVisaEnquiryStatus' : ActorMethod<
    [SessionToken, bigint, string],
    undefined
  >,
  'validateSession' : ActorMethod<[SessionToken], [] | [User]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];