/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SessionToken = IDL.Text;
export const AdminStats = IDL.Record({
  'totalPNREnquiries' : IDL.Nat,
  'totalTourEnquiries' : IDL.Nat,
  'totalFlightEnquiries' : IDL.Nat,
  'totalBookings' : IDL.Nat,
  'totalVisaEnquiries' : IDL.Nat,
  'totalUsers' : IDL.Nat,
});
export const UserBooking = IDL.Record({
  'customerName' : IDL.Text,
  'destination' : IDL.Text,
  'cabinClass' : IDL.Text,
  'paymentStatus' : IDL.Text,
  'bookingId' : IDL.Nat,
  'tripType' : IDL.Text,
  'infantsCount' : IDL.Nat,
  'adultsCount' : IDL.Nat,
  'customerPhone' : IDL.Text,
  'departureDate' : IDL.Text,
  'pnrNumber' : IDL.Opt(IDL.Text),
  'userId' : IDL.Nat,
  'createdAt' : IDL.Int,
  'origin' : IDL.Text,
  'bookingStatus' : IDL.Text,
  'amadeusFlightInfo' : IDL.Opt(IDL.Text),
  'childrenCount' : IDL.Nat,
  'customerEmail' : IDL.Text,
  'returnDate' : IDL.Opt(IDL.Text),
});
export const TripType = IDL.Variant({
  'isFlexible' : IDL.Null,
  'returnTrip' : IDL.Null,
  'oneWay' : IDL.Null,
});
export const FlightEnquiry = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'destination' : IDL.Text,
  'cabinClass' : IDL.Opt(IDL.Text),
  'tripType' : TripType,
  'infantsCount' : IDL.Nat,
  'adultsCount' : IDL.Nat,
  'customerPhone' : IDL.Text,
  'departureDate' : IDL.Text,
  'specialRequests' : IDL.Opt(IDL.Text),
  'origin' : IDL.Text,
  'childrenCount' : IDL.Nat,
  'customerEmail' : IDL.Opt(IDL.Text),
  'returnDate' : IDL.Opt(IDL.Text),
});
export const PNREnquiry = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'customerPhone' : IDL.Text,
  'pnrNumber' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'travelDate' : IDL.Opt(IDL.Text),
  'airline' : IDL.Text,
  'customerEmail' : IDL.Opt(IDL.Text),
});
export const TourEnquiry = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'adultsCount' : IDL.Nat,
  'customerPhone' : IDL.Text,
  'specialRequests' : IDL.Opt(IDL.Text),
  'travelDate' : IDL.Text,
  'tourPackage' : IDL.Text,
  'childrenCount' : IDL.Nat,
  'budget' : IDL.Opt(IDL.Text),
  'customerEmail' : IDL.Opt(IDL.Text),
});
export const User = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'passwordHash' : IDL.Text,
  'isAdmin' : IDL.Bool,
  'phone' : IDL.Opt(IDL.Text),
});
export const VisaEnquiry = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'country' : IDL.Text,
  'customerPhone' : IDL.Text,
  'visaType' : IDL.Text,
  'travelDate' : IDL.Text,
  'passportNumber' : IDL.Opt(IDL.Text),
  'customerEmail' : IDL.Opt(IDL.Text),
  'specialNotes' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Opt(IDL.Text),
});
export const UserBookingInput = IDL.Record({
  'customerName' : IDL.Text,
  'destination' : IDL.Text,
  'cabinClass' : IDL.Text,
  'tripType' : IDL.Text,
  'infantsCount' : IDL.Nat,
  'adultsCount' : IDL.Nat,
  'customerPhone' : IDL.Text,
  'departureDate' : IDL.Text,
  'origin' : IDL.Text,
  'childrenCount' : IDL.Nat,
  'customerEmail' : IDL.Text,
  'returnDate' : IDL.Opt(IDL.Text),
});
export const FlightEnquiryInput = IDL.Record({
  'customerName' : IDL.Text,
  'destination' : IDL.Text,
  'cabinClass' : IDL.Opt(IDL.Text),
  'tripType' : TripType,
  'infantsCount' : IDL.Nat,
  'adultsCount' : IDL.Nat,
  'customerPhone' : IDL.Text,
  'departureDate' : IDL.Text,
  'specialRequests' : IDL.Opt(IDL.Text),
  'origin' : IDL.Text,
  'childrenCount' : IDL.Nat,
  'customerEmail' : IDL.Opt(IDL.Text),
  'returnDate' : IDL.Opt(IDL.Text),
});
export const PNREnquiryInput = IDL.Record({
  'customerName' : IDL.Text,
  'customerPhone' : IDL.Text,
  'pnrNumber' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'travelDate' : IDL.Opt(IDL.Text),
  'airline' : IDL.Text,
  'customerEmail' : IDL.Opt(IDL.Text),
});
export const TourEnquiryInput = IDL.Record({
  'customerName' : IDL.Text,
  'adultsCount' : IDL.Nat,
  'customerPhone' : IDL.Text,
  'specialRequests' : IDL.Opt(IDL.Text),
  'travelDate' : IDL.Text,
  'tourPackage' : IDL.Text,
  'childrenCount' : IDL.Nat,
  'budget' : IDL.Opt(IDL.Text),
  'customerEmail' : IDL.Opt(IDL.Text),
});
export const VisaEnquiryInput = IDL.Record({
  'customerName' : IDL.Text,
  'country' : IDL.Text,
  'customerPhone' : IDL.Text,
  'visaType' : IDL.Text,
  'travelDate' : IDL.Text,
  'passportNumber' : IDL.Opt(IDL.Text),
  'customerEmail' : IDL.Opt(IDL.Text),
  'specialNotes' : IDL.Opt(IDL.Text),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAdminStats' : IDL.Func([SessionToken], [AdminStats], ['query']),
  'getAllBookings' : IDL.Func(
      [SessionToken],
      [IDL.Vec(UserBooking)],
      ['query'],
    ),
  'getAllFlightEnquiries' : IDL.Func(
      [SessionToken],
      [IDL.Vec(IDL.Tuple(IDL.Nat, FlightEnquiry))],
      ['query'],
    ),
  'getAllPNREnquiries' : IDL.Func(
      [SessionToken],
      [IDL.Vec(IDL.Tuple(IDL.Nat, PNREnquiry))],
      ['query'],
    ),
  'getAllTourEnquiries' : IDL.Func(
      [SessionToken],
      [IDL.Vec(IDL.Tuple(IDL.Nat, TourEnquiry))],
      ['query'],
    ),
  'getAllUsers' : IDL.Func(
      [SessionToken],
      [IDL.Vec(IDL.Tuple(IDL.Nat, User))],
      ['query'],
    ),
  'getAllVisaEnquiries' : IDL.Func(
      [SessionToken],
      [IDL.Vec(IDL.Tuple(IDL.Nat, VisaEnquiry))],
      ['query'],
    ),
  'getAmadeusFlightInfo' : IDL.Func(
      [SessionToken, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserBookings' : IDL.Func(
      [SessionToken],
      [IDL.Vec(UserBooking)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'loginUser' : IDL.Func([IDL.Text, IDL.Text], [SessionToken], []),
  'registerUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [SessionToken],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveUserBooking' : IDL.Func([SessionToken, UserBookingInput], [IDL.Nat], []),
  'submitFlightEnquiry' : IDL.Func([FlightEnquiryInput], [IDL.Nat], []),
  'submitPNREnquiry' : IDL.Func([PNREnquiryInput], [IDL.Nat], []),
  'submitTourEnquiry' : IDL.Func([TourEnquiryInput], [IDL.Nat], []),
  'submitVisaEnquiry' : IDL.Func([VisaEnquiryInput], [IDL.Nat], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateBookingPNR' : IDL.Func([SessionToken, IDL.Nat, IDL.Text], [], []),
  'updateBookingPaymentStatus' : IDL.Func(
      [SessionToken, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'updateBookingStatus' : IDL.Func([SessionToken, IDL.Nat, IDL.Text], [], []),
  'updateFlightEnquiryStatus' : IDL.Func(
      [SessionToken, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'updateTourEnquiryStatus' : IDL.Func(
      [SessionToken, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'updateVisaEnquiryStatus' : IDL.Func(
      [SessionToken, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'validateSession' : IDL.Func([SessionToken], [IDL.Opt(User)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SessionToken = IDL.Text;
  const AdminStats = IDL.Record({
    'totalPNREnquiries' : IDL.Nat,
    'totalTourEnquiries' : IDL.Nat,
    'totalFlightEnquiries' : IDL.Nat,
    'totalBookings' : IDL.Nat,
    'totalVisaEnquiries' : IDL.Nat,
    'totalUsers' : IDL.Nat,
  });
  const UserBooking = IDL.Record({
    'customerName' : IDL.Text,
    'destination' : IDL.Text,
    'cabinClass' : IDL.Text,
    'paymentStatus' : IDL.Text,
    'bookingId' : IDL.Nat,
    'tripType' : IDL.Text,
    'infantsCount' : IDL.Nat,
    'adultsCount' : IDL.Nat,
    'customerPhone' : IDL.Text,
    'departureDate' : IDL.Text,
    'pnrNumber' : IDL.Opt(IDL.Text),
    'userId' : IDL.Nat,
    'createdAt' : IDL.Int,
    'origin' : IDL.Text,
    'bookingStatus' : IDL.Text,
    'amadeusFlightInfo' : IDL.Opt(IDL.Text),
    'childrenCount' : IDL.Nat,
    'customerEmail' : IDL.Text,
    'returnDate' : IDL.Opt(IDL.Text),
  });
  const TripType = IDL.Variant({
    'isFlexible' : IDL.Null,
    'returnTrip' : IDL.Null,
    'oneWay' : IDL.Null,
  });
  const FlightEnquiry = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'destination' : IDL.Text,
    'cabinClass' : IDL.Opt(IDL.Text),
    'tripType' : TripType,
    'infantsCount' : IDL.Nat,
    'adultsCount' : IDL.Nat,
    'customerPhone' : IDL.Text,
    'departureDate' : IDL.Text,
    'specialRequests' : IDL.Opt(IDL.Text),
    'origin' : IDL.Text,
    'childrenCount' : IDL.Nat,
    'customerEmail' : IDL.Opt(IDL.Text),
    'returnDate' : IDL.Opt(IDL.Text),
  });
  const PNREnquiry = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'customerPhone' : IDL.Text,
    'pnrNumber' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'travelDate' : IDL.Opt(IDL.Text),
    'airline' : IDL.Text,
    'customerEmail' : IDL.Opt(IDL.Text),
  });
  const TourEnquiry = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'adultsCount' : IDL.Nat,
    'customerPhone' : IDL.Text,
    'specialRequests' : IDL.Opt(IDL.Text),
    'travelDate' : IDL.Text,
    'tourPackage' : IDL.Text,
    'childrenCount' : IDL.Nat,
    'budget' : IDL.Opt(IDL.Text),
    'customerEmail' : IDL.Opt(IDL.Text),
  });
  const User = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'passwordHash' : IDL.Text,
    'isAdmin' : IDL.Bool,
    'phone' : IDL.Opt(IDL.Text),
  });
  const VisaEnquiry = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'country' : IDL.Text,
    'customerPhone' : IDL.Text,
    'visaType' : IDL.Text,
    'travelDate' : IDL.Text,
    'passportNumber' : IDL.Opt(IDL.Text),
    'customerEmail' : IDL.Opt(IDL.Text),
    'specialNotes' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Opt(IDL.Text),
  });
  const UserBookingInput = IDL.Record({
    'customerName' : IDL.Text,
    'destination' : IDL.Text,
    'cabinClass' : IDL.Text,
    'tripType' : IDL.Text,
    'infantsCount' : IDL.Nat,
    'adultsCount' : IDL.Nat,
    'customerPhone' : IDL.Text,
    'departureDate' : IDL.Text,
    'origin' : IDL.Text,
    'childrenCount' : IDL.Nat,
    'customerEmail' : IDL.Text,
    'returnDate' : IDL.Opt(IDL.Text),
  });
  const FlightEnquiryInput = IDL.Record({
    'customerName' : IDL.Text,
    'destination' : IDL.Text,
    'cabinClass' : IDL.Opt(IDL.Text),
    'tripType' : TripType,
    'infantsCount' : IDL.Nat,
    'adultsCount' : IDL.Nat,
    'customerPhone' : IDL.Text,
    'departureDate' : IDL.Text,
    'specialRequests' : IDL.Opt(IDL.Text),
    'origin' : IDL.Text,
    'childrenCount' : IDL.Nat,
    'customerEmail' : IDL.Opt(IDL.Text),
    'returnDate' : IDL.Opt(IDL.Text),
  });
  const PNREnquiryInput = IDL.Record({
    'customerName' : IDL.Text,
    'customerPhone' : IDL.Text,
    'pnrNumber' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'travelDate' : IDL.Opt(IDL.Text),
    'airline' : IDL.Text,
    'customerEmail' : IDL.Opt(IDL.Text),
  });
  const TourEnquiryInput = IDL.Record({
    'customerName' : IDL.Text,
    'adultsCount' : IDL.Nat,
    'customerPhone' : IDL.Text,
    'specialRequests' : IDL.Opt(IDL.Text),
    'travelDate' : IDL.Text,
    'tourPackage' : IDL.Text,
    'childrenCount' : IDL.Nat,
    'budget' : IDL.Opt(IDL.Text),
    'customerEmail' : IDL.Opt(IDL.Text),
  });
  const VisaEnquiryInput = IDL.Record({
    'customerName' : IDL.Text,
    'country' : IDL.Text,
    'customerPhone' : IDL.Text,
    'visaType' : IDL.Text,
    'travelDate' : IDL.Text,
    'passportNumber' : IDL.Opt(IDL.Text),
    'customerEmail' : IDL.Opt(IDL.Text),
    'specialNotes' : IDL.Opt(IDL.Text),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAdminStats' : IDL.Func([SessionToken], [AdminStats], ['query']),
    'getAllBookings' : IDL.Func(
        [SessionToken],
        [IDL.Vec(UserBooking)],
        ['query'],
      ),
    'getAllFlightEnquiries' : IDL.Func(
        [SessionToken],
        [IDL.Vec(IDL.Tuple(IDL.Nat, FlightEnquiry))],
        ['query'],
      ),
    'getAllPNREnquiries' : IDL.Func(
        [SessionToken],
        [IDL.Vec(IDL.Tuple(IDL.Nat, PNREnquiry))],
        ['query'],
      ),
    'getAllTourEnquiries' : IDL.Func(
        [SessionToken],
        [IDL.Vec(IDL.Tuple(IDL.Nat, TourEnquiry))],
        ['query'],
      ),
    'getAllUsers' : IDL.Func(
        [SessionToken],
        [IDL.Vec(IDL.Tuple(IDL.Nat, User))],
        ['query'],
      ),
    'getAllVisaEnquiries' : IDL.Func(
        [SessionToken],
        [IDL.Vec(IDL.Tuple(IDL.Nat, VisaEnquiry))],
        ['query'],
      ),
    'getAmadeusFlightInfo' : IDL.Func(
        [SessionToken, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserBookings' : IDL.Func(
        [SessionToken],
        [IDL.Vec(UserBooking)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'loginUser' : IDL.Func([IDL.Text, IDL.Text], [SessionToken], []),
    'registerUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [SessionToken],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveUserBooking' : IDL.Func(
        [SessionToken, UserBookingInput],
        [IDL.Nat],
        [],
      ),
    'submitFlightEnquiry' : IDL.Func([FlightEnquiryInput], [IDL.Nat], []),
    'submitPNREnquiry' : IDL.Func([PNREnquiryInput], [IDL.Nat], []),
    'submitTourEnquiry' : IDL.Func([TourEnquiryInput], [IDL.Nat], []),
    'submitVisaEnquiry' : IDL.Func([VisaEnquiryInput], [IDL.Nat], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateBookingPNR' : IDL.Func([SessionToken, IDL.Nat, IDL.Text], [], []),
    'updateBookingPaymentStatus' : IDL.Func(
        [SessionToken, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'updateBookingStatus' : IDL.Func([SessionToken, IDL.Nat, IDL.Text], [], []),
    'updateFlightEnquiryStatus' : IDL.Func(
        [SessionToken, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'updateTourEnquiryStatus' : IDL.Func(
        [SessionToken, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'updateVisaEnquiryStatus' : IDL.Func(
        [SessionToken, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'validateSession' : IDL.Func([SessionToken], [IDL.Opt(User)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };