/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TripType = IDL.Variant({
  'isFlexible' : IDL.Null,
  'returnTrip' : IDL.Null,
  'oneWay' : IDL.Null,
});
export const FlightEnquiry = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'destination' : IDL.Text,
  'tripType' : TripType,
  'customerPhone' : IDL.Text,
  'departureDate' : IDL.Text,
  'specialRequests' : IDL.Opt(IDL.Text),
  'origin' : IDL.Text,
  'passengerCount' : IDL.Nat,
  'timestamp' : IDL.Int,
  'customerEmail' : IDL.Opt(IDL.Text),
  'returnDate' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Opt(IDL.Text),
});
export const FlightEnquiryInput = IDL.Record({
  'customerName' : IDL.Text,
  'destination' : IDL.Text,
  'tripType' : TripType,
  'customerPhone' : IDL.Text,
  'departureDate' : IDL.Text,
  'specialRequests' : IDL.Opt(IDL.Text),
  'origin' : IDL.Text,
  'passengerCount' : IDL.Nat,
  'customerEmail' : IDL.Opt(IDL.Text),
  'returnDate' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllEnquiries' : IDL.Func([], [IDL.Vec(FlightEnquiry)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitEnquiry' : IDL.Func([FlightEnquiryInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TripType = IDL.Variant({
    'isFlexible' : IDL.Null,
    'returnTrip' : IDL.Null,
    'oneWay' : IDL.Null,
  });
  const FlightEnquiry = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'destination' : IDL.Text,
    'tripType' : TripType,
    'customerPhone' : IDL.Text,
    'departureDate' : IDL.Text,
    'specialRequests' : IDL.Opt(IDL.Text),
    'origin' : IDL.Text,
    'passengerCount' : IDL.Nat,
    'timestamp' : IDL.Int,
    'customerEmail' : IDL.Opt(IDL.Text),
    'returnDate' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Opt(IDL.Text),
  });
  const FlightEnquiryInput = IDL.Record({
    'customerName' : IDL.Text,
    'destination' : IDL.Text,
    'tripType' : TripType,
    'customerPhone' : IDL.Text,
    'departureDate' : IDL.Text,
    'specialRequests' : IDL.Opt(IDL.Text),
    'origin' : IDL.Text,
    'passengerCount' : IDL.Nat,
    'customerEmail' : IDL.Opt(IDL.Text),
    'returnDate' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllEnquiries' : IDL.Func([], [IDL.Vec(FlightEnquiry)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitEnquiry' : IDL.Func([FlightEnquiryInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };