/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FlightEnquiry {
  'id' : bigint,
  'customerName' : string,
  'destination' : string,
  'tripType' : TripType,
  'customerPhone' : string,
  'departureDate' : string,
  'specialRequests' : [] | [string],
  'origin' : string,
  'passengerCount' : bigint,
  'timestamp' : bigint,
  'customerEmail' : [] | [string],
  'returnDate' : [] | [string],
}
export interface FlightEnquiryInput {
  'customerName' : string,
  'destination' : string,
  'tripType' : TripType,
  'customerPhone' : string,
  'departureDate' : string,
  'specialRequests' : [] | [string],
  'origin' : string,
  'passengerCount' : bigint,
  'customerEmail' : [] | [string],
  'returnDate' : [] | [string],
}
export type TripType = { 'isFlexible' : null } |
  { 'returnTrip' : null } |
  { 'oneWay' : null };
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllEnquiries' : ActorMethod<[], Array<FlightEnquiry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitEnquiry' : ActorMethod<[FlightEnquiryInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];